AllCops:
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - lib/tasks/**/*
    - bin/**/*
    - test/**/*
    - vendor/**/*
    - tmp/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 10

Style/Documentation:
  Enabled: false

# namespace modules do not require empty lines, mixins do.
Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Rails/Delegate:
  Enabled: false
