require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - bin/**/*
    - config/**/*
    - db/**/*
    - dist/**/*
    - lib/tasks/**/*
    - test/**/*
    - tmp/**/*
    - vendor/**/*

# namespace modules do not require empty lines, mixins do.
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

# Long Blocks used for swagger documentation, otherwise handled by method length.
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/SymbolArray:
  Enabled: false

Rails/Delegate:
  Enabled: false

# with dry_crud, this is a pattern
Rails/LexicallyScopedActionFilter:
  Enabled: false

# we should know about update_all constraints.
Rails/SkipsModelValidations:
  Enabled: false
