AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - lib/tasks/**/*
    - bin/**/*
    - test/**/*
    - vendor/**/*
    - tmp/**/*

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 8

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Rails/Delegate:
  Enabled: false
