language: ruby

rvm:
 - '2.5.3'

env:
  global:
    - RAAR_DB_ADAPTER=postgresql
    - RAAR_DB_NAME=raar_test
    - RAAR_DB_USERNAME=postgres
    - AIRTIME_DB_ADAPTER=postgresql
    - AIRTIME_DB_NAME=airtime_test
    - AIRTIME_DB_USERNAME=postgres

sudo: false

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database raar_test;' -U postgres
  - psql -c 'create database airtime_test;' -U postgres

script:
  - bundle exec rails test
  - bundle exec rubocop

before_deploy:
  - bundle exec rails package

deploy:
  provider: releases
  api_key:
    secure: fh7NHL+tXwbz9xE0+J/YHpyUjHYKLXVQZQR2W0J5W/uv1gslMLVPXkedfX/KK3b9XEq+Zj0OnNrXfVOcgmbElMU8mhy1Imx6+v0kcadD9QgmNGf+qKqoDAv5Xs7CX1XoC1Og7PIflLN3aHqypswJ8YfDuY1wmfNlr1yBv2P9pV4oBb122FM4rJxiKvGWz40HebmSPfE4/ZBclP80FlKVLYpdiog8MemqvQqy9dJQ0FnZnCQ/KXujyBOXsl3xoiVxNsqDNeJzq+2ZumVYfsIaDBFxXNQMaScPeVdbzB/f0kPFCasDMV8eKkTmvFipOZwjo/Jo8bMjs+6Xz17Gl/4urc+kygAMMsi/OVZxaKsxUndYUrafCKaWKyr+DMxSryvENqq1i1PzbZrkhrYctl6kyr9ccBBMUK9ChRF0L0XROFGup4POn5kEV96G/705GmiiC+3pGoUnUsxMSERRLlvj7/Rl7+FsJZi9FjAxa0sbaR5s7VPxanMwSAkdODqrcmHXJwEPjungPJbX3gdRMOAKt5+MSUxNfFRCVN3hFAWtqHFriOOH5yaXB5tC8r+wnXylvgtXW4IwUr6HIT0Ip7AZfTbgluedRcIGk10qIpQvfHIYUM9qeOTjy73m7GEEGogLLW07Z3cQXo12C2++9xltjnSfv5Tkzz5FNk3HlymUTso=
  file: dist/raar.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: radiorabe/raar

