# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc98b10ea2349020eaddd33c1bb8d441b0f066562a96444ee90ca7e9c4530d8c369c1a6fbf90b5778b617659aef8329238c9dfe6b1056e7b8011f28734fa44db
  archive_home: <%= Rails.root.join('tmp', 'development', 'archive') %>
  import_directories:
    <% dirs = ENV['IMPORT_DIRECTORIES'] || Rails.root.join('tmp', 'development', 'import')
       dirs.to_s.strip.split(',').each do |d| %>
    - <%= d.strip %>
    <% end %>
  days_to_keep_imported: <%= ENV['DAYS_TO_KEEP_IMPORTED'] || 1 %>
  days_to_finish_import: <%= ENV['DAYS_TO_FINISH_IMPORT'] || 1 %>
  parallel_transcodings: 4
  ssl: false
  host_name: localhost:3000
  base_path:
  admin_groups: 'admins, root'
  days_to_expire_api_key:
  minutes_to_expire_jwt_token: 60

test:
  secret_key_base: ce33a7e3417c30e6f6251a101267068a9a2e7513f7d4f7c6264afccbaa3bfd8f9b6d3f72762d5434140f423f357d9a85b1f01c9c9a59b231ca43e1ea8e655fc1
  archive_home: <%= Rails.root.join('tmp', 'test', 'archive') %>
  import_directories:
    - <%= Rails.root.join('tmp', 'test', 'import') %>
  days_to_keep_imported: 1
  days_to_finish_import: 1
  parallel_transcodings: 4
  ssl: false
  host_name: example.com
  base_path:
  admin_groups: 'admins, root'
  days_to_expire_api_key:
  minutes_to_expire_jwt_token: 60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  archive_home: <%= ENV['ARCHIVE_HOME'] %>
  import_directories:
    <% ENV['IMPORT_DIRECTORIES'].to_s.strip.split(',').each do |d| %>
    - <%= d.strip %>
    <% end %>
  days_to_keep_imported: <%= ENV['DAYS_TO_KEEP_IMPORTED'] %>
  days_to_finish_import: <%= ENV['DAYS_TO_FINISH_IMPORT'] %>
  parallel_transcodings: <%= ENV['PARALLEL_TRANSCODINGS'] || 1 %>
  import_default_show_id: <%= ENV['IMPORT_DEFAULT_SHOW_ID'] %>
  ssl: <%= ENV['RAAR_SSL'] == 'true' %>
  host_name: <%= ENV['RAAR_HOST_NAME'] %>
  base_path: <%= ENV['RAAR_BASE_PATH'] %>
  admin_groups: <%= ENV['RAAR_ADMIN_GROUPS'] || 'admins,root' %>
  days_to_expire_api_key: <%= ENV['DAYS_TO_EXPIRE_API_KEY'] %>
  minutes_to_expire_jwt_token: <%= ENV['MINUTES_TO_EXPIRE_JWT_TOKEN'] || 60 %>
