# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc98b10ea2349020eaddd33c1bb8d441b0f066562a96444ee90ca7e9c4530d8c369c1a6fbf90b5778b617659aef8329238c9dfe6b1056e7b8011f28734fa44db
  archive_home: <%= Rails.root.join('tmp', 'archive') %>
  import_directories:
    - <%= Rails.root.join('tmp', 'import') %>
  days_to_keep_imported: 1

test:
  secret_key_base: ce33a7e3417c30e6f6251a101267068a9a2e7513f7d4f7c6264afccbaa3bfd8f9b6d3f72762d5434140f423f357d9a85b1f01c9c9a59b231ca43e1ea8e655fc1
  archive_home: <%= Rails.root.join('tmp', 'archive') %>
  import_directories:
    - <%= Rails.root.join('tmp', 'import') %>
  days_to_keep_imported: 1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  archive_home: <%= ENV['ARCHIVE_HOME'] %>
  import_directories:
    <% ENV['IMPORT_DIRECTORIES'].to_s.strip.split(',') do |d| %>
    - <%= d.strip %>
    <% end %>
  days_to_keep_imported: <%= ENV['DAYS_TO_KEEP_IMPORTED'] || 1 %>
